# Generated by Django 3.2.7 on 2021-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
